---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - ansible-role-docker
    - ansible-role-docker-compose
    
  vars:
    docker_daemon_dns: ["8.8.8.8"]
    docker_daemon_storage_driver: aufs
